kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: podset-operator2
subjects:
- kind: ServiceAccount
  name: podset-operator2
roleRef:
  kind: Role
  name: podset-operator2
  apiGroup: rbac.authorization.k8s.io
